### PR TITLE
Prepare for the first release

### PR DESCRIPTION
**Pull request by crazytonyli**
I'll create a GitHub release 0.1.0 after this PR is merged.

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
Note 1: You might want to quick-fix https://github.com/Automattic/nvm-buildkite-plugin/pull/3#discussion_r1302759993 before releasing this first version. Feel free to fix it directly as part of this PR (might not be worth it to create a separate PR for just a tiny change) before merging.

Note 2: I think in the next iteration/version of the plugin, we should add the proper CI checks in the Buildkite pipeline.yml, to validate the plugin (using Buildkite's own `buildkite-plugin-lint`/`buildkite-plugin-test`, as well as running `shellcheck` on the `hooks/` scripts), similar to [those we have in a8c-ci-toolkit](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/blob/trunk/Makefile), so that we are sure the plugin is valid before releasing a new version and creating a tag.

For example, one of the things that the `buildkite-plugin-linter` would have complained about before you do this first release is that the [version used in the example of the `README.md`](https://github.com/Automattic/nvm-buildkite-plugin/blob/main/README.md?plain=1#L13) is `#v1.0.0` not the `0.1.0` version number you plan to release 🙃

**Comment by crazytonyli** [comment]
> For example, one of the things that the buildkite-plugin-linter would have complained about before you do this first release is that the [version used in the example of the README.md](https://github.com/Automattic/nvm-buildkite-plugin/blob/main/README.md?plain=1#L13) is #v1.0.0 not the 0.1.0 version number you plan to release 🙃

[The linter](https://github.com/Automattic/nvm-buildkite-plugin/blob/98cc77d58b10fc66f079f886ddb350d2fd24ba15/Makefile#L2) is part of the pipeline at the moment. But I'm not very familiar with it. Do you know how to make it throw the version warning you mentioned?

**Comment by AliSoftware** [comment]
> > For example, one of the things that the buildkite-plugin-linter would have complained about before you do this first release is that the [version used in the example of the README.md](https://github.com/Automattic/nvm-buildkite-plugin/blob/main/README.md?plain=1#L13) is #v1.0.0 not the 0.1.0 version number you plan to release 🙃
> 
> [The linter](https://github.com/Automattic/nvm-buildkite-plugin/blob/98cc77d58b10fc66f079f886ddb350d2fd24ba15/Makefile#L2) is part of the pipeline at the moment. But I'm not very familiar with it. Do you know how to make it throw the version warning you mentioned?

I actually dug into this a bit, because according to my understanding of the `buildkite-plugin-linter`, that run via `make validate` should have warned us. But after [looking at the source code of the linter plugin](https://github.com/buildkite-plugins/buildkite-plugin-linter/blob/master/lib/linters/readme-version-number-linter.js#L37), it turns out that it will only warn us if the version in the README.md is **less than** the latest version.

Currently our `README.md` says `1.0.0` while the latest published version is `0.1.0`… so it doesn't complain. If I change the `README.md` to use `automattic/nvm#0.0.7` then it does indeed complain like this:
```
$ make validate
docker run -it --rm -v "/Users/olivierhalligon/Documents/Dev/tools/nvm-buildkite-plugin:/plugin:ro" buildkite/plugin-linter --id automattic/nvm
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
TAP version 13
ok 1 - plugin.yml configuration is valid
ok 2 - All the readme config examples for plugin id 'automattic/nvm' are valid (1 found)
not ok 3 - Readme version numbers out of date. Latest is 0.1.0
  ---
  invalid version numbers:
    - 0.0.7
  ...

1..3
# failed 1 of 3 tests
```

I'm not sure why their test is just `<` thus allowing our `README.md` to still use an invalid version (as tag `1.0.0` referenced in our README doesn't even exist) 🤔  Though that might be to allow us to prepare the update of the `README.md` before we tag the corresponding version (i.e. if current version was `1.2.0` and we were preparing `1.3.0` we'd have a PR that updates the `README` to `1.3.0` just before creating the `1.3.0` tag and we don't want the checks in the PR to fail just because the tag is not created yet (but will be right after the PR is merged)?

Anyway, that's on me for missing that `make validate` was already calling the `buildkite-plugin-linter`, and this should all be good after all 🙂

**Comment by crazytonyli** [comment]
TIL. Thanks for looking into how the plugin works!

**Pull request merged**
